#Super user permissions reqiured to execute this build
sudo: reqiured
language: generic
#Tell TravisCI that we nee docker cli installed
services:
  - docker

#Will execute a series of commands before our build is ran
before_install:
  - docker build -t dev/react -f Dockerfile.dev .

#https://facebook.github.io/create-react-app/docs/running-tests#linux-macos-bash
#CI=true - will force to run in CI-mode, and test will only run once instead of watcher.
#--watchAll=false - for non-CI enviroments to disable test watching
script:
  - docker run -e CI=true dev/react npm run test

#https://docs.docker.com/engine/reference/run/#env-environment-variables
#Enviromental variables

#Tell TravisCI how to take configurations and deploy to AWS
deploy:
  #Use this set of instruction to deploy the app
  provider: elasticbeanstalk
  region: "us-west-2"
  #Same as Application name created on AWS
  app: "docker-react"
  #Same as Enviroment name created on AWS. Spesific to each app
  env: "Dockerreaact-env"
  #S3 bucket on AWS
  bucket_name: "elasticbeanstalk-us-west-2-837903213847"
  #Path to the app in S3 bucket. Not created by default. would be the same as the app name
  bucket_path: "docker-react"
  #To deploy new app version only if there were changes to master (prod) version
  on:
    branch: master

  #Recall API keys as enviromental variables from TravisCI
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: ""$AWS_SECRET_KEY"
